# Public configuration class
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://gz-cynosdbmysql-grp-osm3y97f.sql.tencentcdb.com:20297/binapi?serverTimezone=Asia/Shanghai
    username: root
    password: Abin214289!!

  # redis
  redis:
    database: 0
    host: localhost
    port: 6379
    isPassword: 0


dubbo:
  application:
    name: bin-api-admin-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://10.0.8.10:8848