spring:
  redis:
    database: 1
    host: localhost
    port: 6379
    isPassword: 0

dubbo:
  application:
    name: bin-api-admin-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://10.0.8.10:8848